---
driver_plugin: docker_cli

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.6

suites:
  - name: default
    driver_config:
      publish: 8080:8080
    run_list:
      - recipe[jenkins::default]
    attributes:
      jenkins:
        listen_address: 0.0.0.0
        ajp_listen_address: 127.0.0.1
        args: -prefix=/jenkins
