---
driver_plugin: docker

driver_config:
  use_sudo: false

provisioner:
  name: chef_solo

platforms:
  - name: centos-5.8
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[jenkins::default]
    attributes:

busser:
  sudo: true
